"""Статический словарь описаний инструментов: operationId -> русское описание.

Описания короткие, однострочные, в инфинитиве/именной форме — как ожидают
LLM-клиенты при выборе инструмента. Покрытие: все 114 operationId спеки.
"""

DESCRIPTIONS: dict[str, str] = {
    # Monitoring
    "ping": "Проверка доступности REST-сервиса Planfix",
    # Workspaces / System
    "get-workspaces": "Список рабочих областей аккаунта",
    "post-integration-telegram-bot-webhook": "Управление настройками Telegram-бота",
    # Object
    "get-object-list": "Список объектов",
    "get-object-by-id": "Объект по номеру",
    "get-object-task-status-list": "Список статусов задач объекта",
    # Comments
    "get-comment-list": "Список комментариев",
    "get-comment-id": "Комментарий по номеру",
    "delete-comment-id": "Удалить комментарий",
    # Tasks
    "get-task-list": "Список задач по фильтру",
    "get-task-by-id": "Задача по номеру",
    "post-task": "Создать задачу",
    "post-task-by-id": "Обновить задачу по номеру",
    "get-task-list-templates": "Список шаблонов задач",
    "get-task-list-recurring": "Список периодических задач",
    "post-task-filters": "Список фильтров задач",
    "get-task-files": "Файлы, прикреплённые к задаче",
    "get-task-process-list": "Список процессов задачи",
    "get-task-status-list": "Список статусов задач процесса",
    "get-task-checklist": "Чек-лист задачи",
    "get-checklist-item-by-id": "Пункт чек-листа по номеру",
    "post-checklist-item": "Создать пункт чек-листа",
    "post-checklist-item-by-id": "Обновить пункт чек-листа",
    # Task comments
    "get-task-comments": "Комментарии к задаче",
    "post-task-add-comment": "Добавить комментарий к задаче",
    "post-task-update-comment": "Обновить комментарий к задаче",
    "post-task-add-data-tag-entry-new-comment": "Добавить значение доп. поля в новый комментарий задачи",
    "post-task-add-data-tag-entry-existing-comment": "Добавить значение доп. поля в существующий комментарий задачи",
    # Contacts
    "get-contact-list": "Список контактов и компаний",
    "get-contact-by-id": "Контакт по номеру",
    "post-contact": "Создать контакт или компанию",
    "post-contact-by-id": "Обновить контакт по номеру",
    "post-contact-import": "Импортировать список контактов",
    "get-contact-list-templates": "Шаблоны контактов и компаний",
    "get-contact-list-groups": "Группы контактов",
    "post-contact-filters": "Список фильтров контактов",
    "get-contact-files": "Файлы, прикреплённые к контакту",
    "get-contact-process-list": "Список процессов контакта",
    # Contact comments
    "get-contact-comments": "Комментарии к контакту",
    "post-contact-add-comment": "Добавить комментарий к контакту",
    "post-contact-update-comment": "Обновить комментарий к контакту",
    "post-contact-add-data-tag-entry-new-comment": "Добавить значение доп. поля в новый комментарий контакта",
    "post-contact-add-data-tag-entry-existing-comment": "Добавить значение доп. поля в существующий комментарий контакта",
    # Projects
    "get-project-list": "Список проектов",
    "get-project-by-id": "Проект по номеру",
    "post-project": "Создать проект",
    "post-project-by-id": "Обновить проект по номеру",
    "get-project-files": "Файлы, прикреплённые к проекту",
    "get-project-list-templates": "Шаблоны проектов",
    "get-project-groups": "Группы проектов",
    # Files
    "get-file-id": "Файл по идентификатору",
    "get-file-id-download": "Скачать файл",
    "post-file-upload": "Загрузить файл",
    "post-file-upload-by-url": "Загрузить файл по ссылке",
    "post-file-update": "Обновить файл",
    "delete-file-id": "Удалить файл",
    "attach-file-to-task": "Прикрепить файл к задаче",
    "attach-file-to-contact": "Прикрепить файл к контакту",
    "attach-file-to-project": "Прикрепить файл к проекту",
    # Data tags
    "get-data-tags": "Справочник значений доп. полей (data tags)",
    "get-datatag-id": "Значение доп. поля по идентификатору",
    "get-datatag-entry-key": "Значение доп. поля по ключу",
    "post-list-data-tag-entries": "Список значений доп. полей",
    "post-update-data-tag-entry": "Обновить значение доп. поля",
    "delete-datatag-entry-key": "Удалить значение доп. поля",
    # Directories
    "get-list-directories": "Список справочников",
    "get-directories-groups": "Группы справочников",
    "get-directory-by-id": "Справочник по идентификатору",
    "get-directory-id-entry-key": "Запись справочника по ключу",
    "post-add-directory-entry": "Создать запись справочника",
    "post-update-directory-entry": "Обновить запись справочника",
    "delete-directory-entry-key": "Удалить запись справочника",
    "post-list-directory-entries": "Список записей справочника",
    "post-directory-entries-filters": "Фильтры записей справочника",
    # Custom fields (reads)
    "get-customfield-types": "Типы пользовательских полей",
    "get-customfield-generic": "Список общих пользовательских полей",
    "get-customfield-contact": "Пользовательские поля контакта",
    "get-customfield-task": "Пользовательские поля задачи",
    "get-customfield-project": "Пользовательские поля проекта",
    "get-customfield-user": "Пользовательские поля сотрудника",
    "get-customfield-sets-contact": "Наборы пользовательских полей контакта",
    "get-customfield-sets-task": "Наборы пользовательских полей задачи",
    "get-customfield-sets-project": "Наборы пользовательских полей проекта",
    "get-customfield-sets-user": "Наборы пользовательских полей сотрудника",
    "get-customfields-for-contact": "Все пользовательские поля для контакта",
    "get-customfields-for-task": "Все пользовательские поля для задачи",
    "get-customfields-for-project": "Все пользовательские поля для проекта",
    "get-customfields-for-user": "Все пользовательские поля для сотрудника",
    "get-customfields-for-directory": "Пользовательские поля для справочника",
    "get-customfields-for-datatag": "Пользовательские поля для доп. полей",
    # Custom fields (mutations)
    "post-customfield-add": "Создать пользовательское поле контакта",
    "post-customfield-task-add": "Создать пользовательское поле задачи",
    "post-customfield-project-add": "Создать пользовательское поле проекта",
    "post-customfield-user-add": "Создать пользовательское поле сотрудника",
    "post-customfield-main-add": "Создать общее пользовательское поле",
    "post-customfield-main-update": "Обновить общее пользовательское поле",
    "post-customfield-set-add": "Создать набор пользовательских полей контакта",
    "post-customfield-set-task-add": "Создать набор пользовательских полей задачи",
    "post-customfield-set-project-add": "Создать набор пользовательских полей проекта",
    "post-customfield-set-user-add": "Создать набор пользовательских полей сотрудника",
    # Reports
    "get-report-list": "Список отчётов",
    "get-report-id": "Отчёт по идентификатору",
    "generate-report": "Сформировать отчёт",
    "get-report-save-list": "Список сохранённых отчётов",
    "get-report-save-data": "Данные сохранённого отчёта",
    "check-get-report-save-by-request-id": "Проверить готовность отчёта и получить результат",
    # Users / Employees
    "get-user-list": "Список сотрудников",
    "get-user-id": "Сотрудник по номеру",
    "post-user": "Создать сотрудника",
    "post-user-id": "Обновить сотрудника по номеру",
    "get-user-groups": "Группы сотрудников",
    "get-user-positions": "Должности сотрудников",
    "post-user-positions": "Создать должность сотрудника",
    "post-user-positions-id": "Обновить должность сотрудника",
}