"""Статический словарь имён инструментов: operationId -> короткое snake_case имя.

Имена уникальны: чтения короткие по ресурсу (task_list), мутации получают
глагольный префикс (create_task, update_task, delete_comment), что исключает
коллизии get/post одного ресурса и сохраняет понятность в MCP-клиенте.
"""

NAMES: dict[str, str] = {
    # Monitoring
    "ping": "ping",
    # Workspaces / System
    "get-workspaces": "list_workspaces",
    "post-integration-telegram-bot-webhook": "telegram_bot_webhook",
    # Object
    "get-object-list": "object_list",
    "get-object-by-id": "object_by_id",
    "get-object-task-status-list": "object_task_status_list",
    # Comments
    "get-comment-list": "comment_list",
    "get-comment-id": "comment_by_id",
    "delete-comment-id": "delete_comment",
    # Tasks
    "get-task-list": "task_list",
    "get-task-by-id": "task_by_id",
    "post-task": "create_task",
    "post-task-by-id": "update_task",
    "get-task-list-templates": "task_template_list",
    "get-task-list-recurring": "recurring_task_list",
    "post-task-filters": "task_filters",
    "get-task-files": "task_file_list",
    "get-task-process-list": "task_process_list",
    "get-task-status-list": "task_status_list",
    "get-task-checklist": "task_checklist",
    "get-checklist-item-by-id": "checklist_item_by_id",
    "post-checklist-item": "create_checklist_item",
    "post-checklist-item-by-id": "update_checklist_item",
    # Task comments
    "get-task-comments": "task_comments",
    "post-task-add-comment": "add_task_comment",
    "post-task-update-comment": "update_task_comment",
    "post-task-add-data-tag-entry-new-comment": "add_task_datatag",
    "post-task-add-data-tag-entry-existing-comment": "add_task_datatag_to_comment",
    # Contacts
    "get-contact-list": "contact_list",
    "get-contact-by-id": "contact_by_id",
    "post-contact": "create_contact",
    "post-contact-by-id": "update_contact",
    "post-contact-import": "import_contacts",
    "get-contact-list-templates": "contact_template_list",
    "get-contact-list-groups": "contact_group_list",
    "post-contact-filters": "contact_filters",
    "get-contact-files": "contact_file_list",
    "get-contact-process-list": "contact_process_list",
    # Contact comments
    "get-contact-comments": "contact_comments",
    "post-contact-add-comment": "add_contact_comment",
    "post-contact-update-comment": "update_contact_comment",
    "post-contact-add-data-tag-entry-new-comment": "add_contact_datatag",
    "post-contact-add-data-tag-entry-existing-comment": "add_contact_datatag_to_comment",
    # Projects
    "get-project-list": "project_list",
    "get-project-by-id": "project_by_id",
    "post-project": "create_project",
    "post-project-by-id": "update_project",
    "get-project-files": "project_file_list",
    "get-project-list-templates": "project_template_list",
    "get-project-groups": "project_group_list",
    # Files
    "get-file-id": "file_by_id",
    "get-file-id-download": "download_file",
    "post-file-upload": "upload_file",
    "post-file-upload-by-url": "upload_file_by_url",
    "post-file-update": "update_file",
    "delete-file-id": "delete_file",
    "attach-file-to-task": "attach_file_to_task",
    "attach-file-to-contact": "attach_file_to_contact",
    "attach-file-to-project": "attach_file_to_project",
    # Data tags
    "get-data-tags": "data_tag_list",
    "get-datatag-id": "datatag_by_id",
    "get-datatag-entry-key": "datatag_entry_by_id",
    "post-list-data-tag-entries": "datatag_entry_list",
    "post-update-data-tag-entry": "update_datatag_entry",
    "delete-datatag-entry-key": "delete_datatag_entry",
    # Directories
    "get-list-directories": "directory_list",
    "get-directories-groups": "directory_group_list",
    "get-directory-by-id": "directory_by_id",
    "get-directory-id-entry-key": "directory_entry_by_id",
    "post-add-directory-entry": "create_directory_entry",
    "post-update-directory-entry": "update_directory_entry",
    "delete-directory-entry-key": "delete_directory_entry",
    "post-list-directory-entries": "directory_entry_list",
    "post-directory-entries-filters": "directory_entry_filters",
    # Custom fields (reads)
    "get-customfield-types": "customfield_type_list",
    "get-customfield-generic": "customfield_main_list",
    "get-customfield-contact": "customfield_contact_list",
    "get-customfield-task": "customfield_task_list",
    "get-customfield-project": "customfield_project_list",
    "get-customfield-user": "customfield_user_list",
    "get-customfield-sets-contact": "customfield_set_list_contact",
    "get-customfield-sets-task": "customfield_set_list_task",
    "get-customfield-sets-project": "customfield_set_list_project",
    "get-customfield-sets-user": "customfield_set_list_user",
    "get-customfields-for-contact": "customfields_for_contact",
    "get-customfields-for-task": "customfields_for_task",
    "get-customfields-for-project": "customfields_for_project",
    "get-customfields-for-user": "customfields_for_user",
    "get-customfields-for-directory": "customfields_for_directory",
    "get-customfields-for-datatag": "customfields_for_datatag",
    # Custom fields (mutations)
    "post-customfield-add": "create_customfield_contact",
    "post-customfield-task-add": "create_customfield_task",
    "post-customfield-project-add": "create_customfield_project",
    "post-customfield-user-add": "create_customfield_user",
    "post-customfield-main-add": "create_customfield_main",
    "post-customfield-main-update": "update_customfield_main",
    "post-customfield-set-add": "create_customfield_set_contact",
    "post-customfield-set-task-add": "create_customfield_set_task",
    "post-customfield-set-project-add": "create_customfield_set_project",
    "post-customfield-set-user-add": "create_customfield_set_user",
    # Reports
    "get-report-list": "report_list",
    "get-report-id": "report_by_id",
    "generate-report": "generate_report",
    "get-report-save-list": "report_save_list",
    "get-report-save-data": "report_save_data",
    "check-get-report-save-by-request-id": "check_report_save",
    # Users / Employees
    "get-user-list": "user_list",
    "get-user-id": "user_by_id",
    "post-user": "create_user",
    "post-user-id": "update_user",
    "get-user-groups": "user_group_list",
    "get-user-positions": "user_position_list",
    "post-user-positions": "create_user_position",
    "post-user-positions-id": "update_user_position",
}